name: Publish Python Package

on:
  release:
    types: [published]
    tags:
      - python*

jobs:
  pypi-publish:
    name: Publish release to PyPI
    if: startsWith(github.event.release.name, 'Python')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/starpoint
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      # Commented out to test workflow
      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
