name: Publish Package to npmjs

on:
  release:
    types: [published]
    tags:
      - typescript*


jobs:
  npm-publish:
    name: Publish release to npmjs
    if: startsWith(github.event.release.name, 'Typescript')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      # Commented out to test workflow
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
