name: Python Tests

on:
  push:
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-python-sdk:
    name: Python SDK Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r dev-requirements.txt
      - name: Run Python Unit Tests
        run: |
          pytest ./tests -v
