name: Python Tests

on:
  pull_request:
    types:
      - opened

jobs:
  cancel:
    name: Cancel previous workflows
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Run Python Unit Tests
        run: |
          pytest ./tests -v
